import os
import glob

env = Environment(ENV = os.environ)

env.Append(LIBS=["png"])
env.Append(CXXFLAGS=["-std=c++17","-g","-Wall","-O3","-I/usr/local/include/include"])
env.Append(LINKFLAGS=["-L/usr/local/lib/lib"])

env.Program("driver",["main.cpp","parse.cpp","dump_png.cpp","driver_state.cpp","shaders.cpp"])
